### ISSUE TITLE
Setup development environments

### ISSUE THREAD

**Issue by JimSab** [aldookware/nailguy#3]
Choose *nix or win environments

**Comment by aldookware** [comment]
@JimSab Do we need this open?

**Comment by JimSab** [comment]
@aldookware No we don't. It was only created for illustration purposes.

**Comment by JimSab** [comment]
From our previous meeting we agreed on the following;
1. FrontEnd Technlogies:
     - Native Android, IOS - Swift. 
     - Admin interface: React/redux
2. Backend:
     - Python/Django
3. Database:
    - MongoDB

We also agreed to use Google OAuth to access the google APIs, such as the googlemaps. upon completion the system will be deployed to AWS.

We are yet to agree on our next meeting date,  i propose a one  Thursday 3rd 2019. In this meeting we shall expound on the system functionality.
